// <auto-generated />
namespace CinemaFinal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initialdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201808201228139_initialdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
